version: '3.9'

services:
  app:
    container_name: nextjs-app
    image: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - nextjs-app
    volumes:
      - .:/app
      - /app/node_modules

networks:
  nextjs-app:
    name: nextjs-app

volumes:
  nextjs-app:
    name: nextjs-app
